# Data Retrieval
# Available Sources: YAHOO, TD_AMERITRADE
DATA_SOURCE: YAHOO
API_KEY: Your_API_Key
TICKERS_API: "https://api.tdameritrade.com/v1/marketdata/%s/pricehistory"

# Portfolio Cash Value in $
CASH: 100000
# How many positions you want in the portfolio. Result may not be exact!
POSITIONS_COUNT_TARGET: 10
# How many stocks do you want to see in the end? This is just for info.
STOCKS_COUNT_OUTPUT: 50
# Optional (Remove # sign for use): Instead of using POSITIONS_COUNT_TARGET you can also directly adjust the risk factor in the Clenows risk parity equation
#RISK_FACTOR: 0.002

# Choose your universe!
# Only those stocks are considered which are included in the enabled indexes
NQ100: true
SP500: true
SP400: false
SP600: false

# Calculation
# Standard is 125 (as per second book "Trading Evolved", 90 for the first book), but you can have as many as you want
MOMENTUM_CALCULATION_PAST_DAYS:
  - 90


# If the gap between days is bigger than this percent value, the stock gets excluded
EXCLUDE_MAX_GAP_PCT: 35

# Do you want to exclude stocks if the MA100 is crossed during the whole slope period?
EXCLUDE_ALL_MA_CROSSES: false

# Program behavior
# Should the program wait for you to hit enter to exit?
EXIT_WAIT_FOR_ENTER: false
