name: move workflow

#on: [workflow_dispatch]
  
on:
  schedule:
     - cron: '1 4 * * 6'     #'45 14 * * 1-5' (see https://crontab.guru)

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3.2.0  # checkout the repository content to github runner
        with:
         repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env: 
          GITHUB_TOKEN: ${{ github.token }}
      - name: execute py script
        run: |
          python momentum.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Weekly run"
          git push
        env: 
          GITHUB_TOKEN: ${{ github.token }}




